name: hello_world

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: say hello world
        run: |
          echo "Hello World!"
      - name: Now it is
        run: date
      - name: Directory content
        run: ls -l
